LANG_TEXT = {
    "English": {
        "app_title": "📖 Question Inserter Tool @vipplavAI",
        "choose_action": "Choose an action:",
        "login_label": "Login",
        "register_label": "Register",
        "new_username": "New Username:",
        "new_password": "New Password:",
        "register_btn": "Register",
        "register_success": "User registered successfully! Please login now.",
        "login_username": "Username:",
        "login_password": "Password:",
        "login_btn": "Login",
        "login_error": "Invalid username or password.",
        "welcome_user": "Welcome, {username}!",
        "search_id": "Search content_id:",
        "search_btn": "Search",
        "content_id_retrieved": "📜 Retrieved Content (ID: {content_id})",
        "content_box_label": "Content:",
        "total_questions": "📌 **Total Questions:** {count}",
        "add_new_question_subheader": "📝 Add a New Question",
        "enter_new_q_label": "Enter New Question:",
        "save_question_btn": "Save Question",
    },
    "Telugu": {
        "app_title": "📖 ప్రశ్న ఇన్సర్టర్ సాధనం @vipplavAI",
        "choose_action": "ఒక చర్యను ఎంచుకోండి:",
        "login_label": "లాగిన్",
        "register_label": "రిజిస్టర్",
        "new_username": "క్రొత్త యూజర్ పేరు:",
        "new_password": "క్రొత్త పాస్వర్డ్:",
        "register_btn": "రిజిస్టర్",
        "register_success": "వాడుకరి విజయవంతంగా రిజిస్టర్ అయ్యారు! లాగిన్ అవండి.",
        "login_username": "యూజర్ పేరు:",
        "login_password": "పాస్వర్డ్:",
        "login_btn": "లాగిన్",
        "welcome_user": "సుస్వాగతం, {username}!",
        "search_id": "కంటెంట్ ఐడి వెతకండి:",
        "search_btn": "వెతకండి",
        "content_id_retrieved": "📜 తిరిగి పొందిన కంటెంట్ (ID: {content_id})",
        "content_box_label": "కంటెంట్:",
        "total_questions": "📌 **మొత్తం ప్రశ్నలు:** {count}",
    }
}
